-- Last modification date: 2022-09-29 01:51:13.978

-- foreign keys
ALTER TABLE COOKBOOK_RECIPE
    DROP FOREIGN KEY COOKBOOK_RECIPE_COOKBOOKS;

ALTER TABLE COOKBOOK_RECIPE
    DROP FOREIGN KEY COOKBOOK_RECIPE_RECIPES;

ALTER TABLE RECIPES
    DROP FOREIGN KEY RECIPES_USER;

ALTER TABLE RECIPE_TAGS
    DROP FOREIGN KEY RECIPE_TAGS_RECIPES;

ALTER TABLE RECIPE_TAGS
    DROP FOREIGN KEY RECIPE_TAGS_TAGS;

-- tables
DROP TABLE COOKBOOKS;

DROP TABLE COOKBOOK_RECIPE;

DROP TABLE RECIPES;

DROP TABLE RECIPE_TAGS;

DROP TABLE TAGS;

DROP TABLE USER;

-- End of file.

