delete from tags;
delete from recipes;
delete from cookbooks;
delete from user;
INSERT INTO RecipeTrackerTest.user (user_id, first_name, last_name, email, login_name) VALUES (1, 'Test', 'User1', 'eemclaughlin@madisoncollege.edu', 'testuser1');
INSERT INTO RecipeTrackerTest.user (user_id, first_name, last_name, email, login_name) VALUES (2, 'Peggy', 'Curbs', 'pcurbs@gmail.com', 'CurbsP');
INSERT INTO RecipeTrackerTest.user (user_id, first_name, last_name, email, login_name) VALUES (3, 'Bob', 'Hamelin', 'bobh@outlook.com', 'HamelB');
INSERT INTO RecipeTrackerTest.tags (tag_id, tag_name, description) VALUES (1, 'Rice', 'Rice');
INSERT INTO RecipeTrackerTest.tags (tag_id, tag_name, description) VALUES (2, 'Whole Milk', 'Whole Milk');
INSERT INTO RecipeTrackerTest.tags (tag_id, tag_name, description) VALUES (3, 'Carrots', 'Carrots');
INSERT INTO RecipeTrackerTest.tags (tag_id, tag_name, description) VALUES (4, 'Beef', 'Beef');
INSERT INTO RecipeTrackerTest.cookbooks (cookbook_id, title, author, publisher, user_cd) VALUE (1, 'The Best Cookbook', 'Jean-Luc Picard', 'Enterprise Press', 1);
INSERT INTO RecipeTrackerTest.cookbooks (cookbook_id, title, author, publisher, user_cd) VALUE (2, 'The Next Best Cookbook', 'James T Kirk', 'Enterprise Press', 2);
INSERT INTO RecipeTrackerTest.recipes (recipe_id, recipe_name, description, notes, page_number, user_cd, cookbook_cd) VALUES (1, 'Carrot Cake', null, null, 300, 1, 1);
INSERT INTO RecipeTrackerTest.recipes (recipe_id, recipe_name, description, notes, page_number, user_cd, cookbook_cd) VALUES (2, 'Meatloaf', null, null, 25, 2, 2);
INSERT INTO RecipeTrackerTest.recipes (recipe_id, recipe_name, description, notes, page_number, user_cd, cookbook_cd) VALUES (3, 'Tacos', null, null, 36, 3, 2);
INSERT INTO RecipeTrackerTest.recipes (recipe_id, recipe_name, description, notes, page_number, user_cd, cookbook_cd) VALUES (4, 'Creme Brulee', null, null, 281, 1, 1);