delete from recipes;
delete from cookbooks;
delete from user;
INSERT INTO RecipeTracker.user (user_id, first_name, last_name, login_id, password) VALUES (1, 'Johnny', 'Cash', 'CashJ', 'CashJ');
INSERT INTO RecipeTracker.user (user_id, first_name, last_name, login_id, password) VALUES (2, 'Peggy', 'Curbs', 'CurbsP', 'CurbsP');
INSERT INTO RecipeTracker.user (user_id, first_name, last_name, login_id, password) VALUES (3, 'Bob', 'Hamelin', 'HamelB', 'HamelB');
INSERT INTO RecipeTracker.cookbooks (cookbook_id, title) VALUE (1, 'The Best Cookbook');
INSERT INTO RecipeTracker.cookbooks (cookbook_id, title) VALUE (2, 'The Next Best Cookbook');
INSERT INTO RecipeTracker.recipes (recipe_id, recipe_name, description, notes, page_number, user_cd, cookbook_cd) VALUES (1, 'Carrot Cake', null, null, 300, 1, 1);
INSERT INTO RecipeTracker.recipes (recipe_id, recipe_name, description, notes, page_number, user_cd, cookbook_cd) VALUES (2, 'Meatloaf', null, null, 25, 2, 2);
INSERT INTO RecipeTracker.recipes (recipe_id, recipe_name, description, notes, page_number, user_cd, cookbook_cd) VALUES (3, 'Tacos', null, null, 36, 3, 2);
INSERT INTO RecipeTracker.recipes (recipe_id, recipe_name, description, notes, page_number, user_cd, cookbook_cd) VALUES (4, 'Creme Brulee', null, null, 281, 1, 1);
